import os
import subprocess
import shutil

def generation_workflow_oemer(image_path: str, output_dir: str = "./") -> str:
    """
    I process the music sheet image and generate a MusicXML file using the Oemer Baseline engine.
    I also force the generation of diagnostic images and move everything to the output directory.
    """
    # I extract the filename without extension to know what the XML will be called
    base_name = os.path.splitext(os.path.basename(image_path))[0]
    
    # The expected output XML name generated by oemer
    expected_xml = os.path.join(output_dir, f"{base_name}.musicxml")

    # I construct the exact command line string using the full, explicit flag names
    cmd = [
        "oemer", 
        image_path, 
        "-o", output_dir, 
        "--save-cache",     # I explicitly demand the diagnostic images
        "--without-deskew"  # I skip deskewing, just like in the original Python API call
    ]

    try:
        # I execute the command, waiting for it to finish and capturing any output/errors
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        # If oemer crashes, I send its EXACT terminal error directly to the Streamlit interface
        raise RuntimeError(f"Oemer terminal crash:\n{e.stderr}\n{e.stdout}") from e

    # --- IMAGE RESCUE OPERATION ---
    # I look in the input directory, because oemer stubbornly saves cache images next to the input file
    input_dir = os.path.dirname(os.path.abspath(image_path))
    
    # These are the typical names oemer uses for its cache images
    cache_image_patterns = [
        "staffs.png", 
        "noteheads.png", 
        "clefs_keys.png", 
        "stems_rests.png",
        "bboxes.png"
    ]

    for pattern in cache_image_patterns:
        # I look for the file next to the input image
        source_path = os.path.join(input_dir, pattern)
        if os.path.exists(source_path):
            # If I find it, I securely move it to my testing output directory
            dest_path = os.path.join(output_dir, pattern)
            shutil.move(source_path, dest_path)

    # I verify that the XML file was actually created
    if not os.path.exists(expected_xml):
        # I check if oemer saved it in the input directory instead of the output directory
        fallback_xml = os.path.join(input_dir, f"{base_name}.musicxml")
        if os.path.exists(fallback_xml):
             shutil.move(fallback_xml, expected_xml)
        else:
            raise FileNotFoundError(f"I could not find the expected XML file: {expected_xml}")

    return expected_xml